### ISSUE TITLE
Regex PathMatcher should match on empty segment if empty string matches regex

### ISSUE THREAD

**Issue by zozoens31** [akka/akka-http#1010]
When using a regex that is matched by the empty string, `akka.http.scaladsl.server.PathMatcher._regex2PathMatcher` fails to match on it

    import akka.http.scaladsl.server.{PathMatcher, PathMatcher1}
    import PathMatcher._
    import akka.http.scaladsl.model.Uri.Path

    val regex = "a*".r
    val matcher: PathMatcher1[String] = regex

    assert(regex.findFirstIn("a") == Some("a"))
    assert(regex.findFirstIn("") == Some(""))

    assert(matcher("a" :: Path.Empty) == Matched(Path.Empty, Tuple1("a")))
    assert(matcher("" :: Path.Empty) == Matched(Path.Empty, Tuple1("")))  //AssertionError

**Comment by zozoens31** [comment]
Say you have a route with `PathMatcher("prefix") ~ PathMatcher(".*".r)` (I know you could put `prefix` in the regex, but assume it is any different `PathMatcher` that matches only part of a segment). I would assume that `/prefix/`would be matched, but it is not.

**Comment by jrudolph** [comment]
The reason is that there is no representation of an "empty segment" in `Uri.Path` and the regex matcher only matches on segments. Instead, the expression `"" :: Path.Empty` is automatically simplified to `Path.Empty`.

If we want to fix this, `_regex2PathMatcher` needs to be changed, so that instead of  `case _ => Unmatched` it is checked first if the regex would match the empty string. If someone wants to contribute this with tests I think I'd agree to merge it.
