### ISSUE TITLE
[Discuss] Prevent construction of impossible routes with types

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1021]
This issue falls more into the wishlist area, and I think it makes more sense to consider it if (when) wanting to apply a lifting to the current DSL.
There are some directives that makes no sense to nest inside each other. For example:
- Any of the method directives
- Nest a `pathPrefix` inside a `path`
- Any path directive after `pathEnd`

The current DSL doesn't prevent nor help the developer to catch such errors, and in some cases, it might lead to some wasted time debugging why a route is not called when it should.
It would be good if all those impossible scenarios were caught by the compiler.

Another alternative would be to convince some IDE maintainers to include such checks as warnings.

**Comment by ktoso** [comment]
We can open issues on the intellij issue tracker and mark them as subsystem: akka, I know the guys are looking for ideas for features to implement :)

**Comment by jonas** [comment]
This to me is somewhat related with #201 assuming both require the ability to do introspection on the AST (or abstract route tree). Short of moving to a more static way of representing routes maybe scala.meta can be of use.

**Comment by jrudolph** [comment]
I think it would be overkill to try to fix that with types. We would have to find a simple encoding that would allow to parametrize all `Route` and `Directive` with all of the properties we want to check and then propagate that everywhere correctly. That's just not feasible using the Scala type system.

I think we should rather invest in a generic tracing infrastructure for Akka HTTP routes that would should show the path a request has taken through the routing tree. In the best case it would should better why a path didn't match at a certain point.

A lighter debugging tool could be more informative rejection messages (behind a "debugging mode" config flag) that would directly point to the issue in the rejection coming from the accidental `path` instead of `pathPrefix`.

More generally: one of the problems is that it is always easier to say why a code path was taken but always hard to say why a code path was *not* taken (there are only so many ways to call something, but unlimited ways of not calling something). In Akka HTTP an additional problem is that the route tree is not static but built dynamically so that routes that are not taken are not even existent.

**Comment by jlprat** [comment]
I think I should use the "crazy idea" tag @ktoso was mentioning in some other ticket :smiley:

I agree with a better debugging pointing where a rejection happened and other ones in this direction.

**Comment by raboof** [comment]
I don't see a way we could solve this... closing until we come up with a really crazy idea? :)
