### ISSUE TITLE
akka-http-parsing missing from download page

### ISSUE THREAD

**Issue by revolucion09** [akka/akka-http#1096]
just recently came across a java.lang.NoClassDefFoundError caused because a missing dependency called **akka-parsing**. I had to trace back to maven central repo to find it, I believe it should be part of the akka-http module download links here: http://akka.io/docs/. Aside from the fact that it is called akka-parsing and not called akka-http-parsing

**Comment by jrudolph** [comment]
Thanks, good point, we usually just assume that most people would use a dependency manager which takes care of including everything needed. Since the download page is going to be away soon, we recently added a wget tab on the docs page to help people all the artifacts needed but you are right akka-parsing is missing from there.

**Comment by jonas** [comment]
Made a PR to fix this https://github.com/akka/akka.github.com/pull/384
