### ISSUE TITLE
fileUpload directive does not discard the rest of request body

### ISSUE THREAD

**Issue by maxcom** [akka/akka-http#1216]
We use `fileUpload("filename")` directive to handle request with one input file. Buggy client sent some additional fields (that we do not need) after that file and never got a response (his request was timed out).

We found that `fileUpload("filename")` directive reads only one file from multipart request and does not discard the rest of input stream. If client sends some other fields after that file then he never gets a response.

**Comment by jrudolph** [comment]
Thanks for the report, @maxcom.

Interesting that this should happen because `take(1)` [at this point](https://github.com/akka/akka-http/blob/5932237a86a432d623fafb1e84eeeff56d7485fe/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala#L77-L77) should take care of it.

Could you publish a reproducer somewhere or create a PR with a failing test that would help a lot.

**Comment by maxcom** [comment]
I could not reproduce exact the same problem, but this code reproduces similar case: https://github.com/maxcom/akka-http-bug2.

When I run it a see

```
[WARN] [06/26/2017 19:28:58.891] [abook-slave-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(abook-slave)] Sending an 2xx 'early' response before end of request was received... Note that the connection will be closed after this response. Also, many clients will not read early responses! Consider only issuing this response after the request data has been completely read!
```

I added SSL to this case to show that is actually causes problem for chosen HTTP client.

**Comment by tkroman** [comment]
@jrudolph hi, I tried to tackle this by going through all the parts manually discarding every part that isn't relevant:

```scala
val onePartSource: Future[Option[(FileInfo, Source[ByteString, Any])]] = formData.parts
          .runFoldAsync(Option.empty[(FileInfo, Source[ByteString, Any])]) {
            case (found, part) =>
              found match {
                case None if part.name == fieldName && part.filename.isDefined =>
                  Future.successful(
                    Some((
                      FileInfo(fieldName, part.filename.get, part.entity.contentType),
                      part.entity.dataBytes
                    ))
                  )
                case _ =>
                  part.entity.discardBytes().future.map { _ =>
                    found
                  }
              }
          }
        onSuccess(onePartSource)
```

But I bumped into #73 (or #269, or #961-related issue), I think. When I wrote some tests that used a non-strict `Multipart.FormData.BodyPart`s, I got 

`akka.stream.impl.SubscriptionTimeoutException: Substream Source has not been materialized in 5000 milliseconds```, which is

which is due to the fact the part's entity is neither read nor discarded, if I'm allowed to venture a guess.

WDYT? Am I thinking in the right direction? Would be great to have some input on this.

**Comment by jrudolph** [comment]
I tried to reproduce. I see two different behaviors:

 * curl sees `curl: (55) Send failure: Connection reset by peer`
 * or it "just works", i.e. the client sees the response and the connection is closed right after that (actually the connection is still RST but only after the client has read it)

I think both are understandable given the current implementation. What probably happens is that `take(1)` cancels the request entity stream which will lead to the connection being dropped. This can happen either before the client has seen the response or afterwards.

The underlying problem is that this kind of behavior is not really specified. To be compatible with all kinds of clients the server should first read the complete entity before sending a response. Doing a mixture of both and then resetting the connection will lead to the undefined behavior we are seeing here.

So, I agree, the `fileUpload` directive should probably be changed not to use `take(1)` but to make sure to read all data before sending the response.

**Comment by jrudolph** [comment]
@tkroman the problem with your first solution is that `onePartSource` future will only be completed once all parts have been read. However, all the parts after the relevant one can only be read after the relevant `part.entity.dataBytes` have been read. So, this is basically a deadlock.

**Comment by jrudolph** [comment]
Here's a similar version to yours that wraps the execution of the inner route to call the inner route when the specific file needs to be handled and then continues to read the remaining parts before returning the response:

```scala
  def fileUpload(fieldName: String): Directive1[(FileInfo, Source[ByteString, Any])] =
    entity(as[Multipart.FormData]).flatMap { formData ⇒
      Directive[Tuple1[(FileInfo, Source[ByteString, Any])]] { inner ⇒ ctx ⇒
        import ctx.materializer
        import ctx.executionContext
        formData.parts
          .runFoldAsync(Option.empty[RouteResult]) {
            case (None, part) if part.filename.isDefined && part.name == fieldName ⇒

              val data = (FileInfo(part.name, part.filename.get, part.entity.contentType), part.entity.dataBytes)
              inner(Tuple1(data))(ctx).map(Some(_))

            case (res, part) ⇒
              part.entity.discardBytes()
              Future.successful(res)
          }
          .map(_.getOrElse(RouteResult.Rejected(MissingFormFieldRejection(fieldName) :: Nil)))
      }
    }
```
