### ISSUE TITLE
Provide Dilated Timeouts for Java Testkit

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1271]
As discovered in #1238, Java Testkit can't benefit of the dilated tests.
The current timeout when using Scala Testkit is 1 second (dilated) while the Java one is just 3 seconds.

In order to let Java Testkit use `dilated`, the `RouteTest` should extend `JavaTestKit` (that is where the `dilated` method is defined).

**Comment by jiminhsieh** [comment]
I found `JavaTestKit` prepare to deprecate since Akka 2.5.0. It would be replace by `akka.testkit.javadsl.TestKit`. Do we still need to fix this? I also found `akka.http.javadsl.testkit.RouteTest` could not just simply extend JavaTestKit. It already extended abstract class - `akka.http.javadsl.server.AllDirectives`. Maybe I just misunderstand what your idea. Thanks!

**Comment by jlprat** [comment]
That might well be (deprecation)! I guess I was checking the 2.4.x series (which Akka HTTP depends on).
Basically, what I meant is that https://github.com/akka/akka-http/blob/master/akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/RouteTest.scala#L36 this should have a `dilated` timeout.

**Comment by raboof** [comment]
(just to clarify, in case someone stumbles upon this ticket: while Akka HTTP indeed depends on Akka 2.4.x, it also works with Akka 2.5.x as those are [binary compatible](http://doc.akka.io/docs/akka/current/scala/common/binary-compatibility-rules.html). We plan to update the dependency as part of #1151)

**Comment by jrudolph** [comment]
Fixed in #1272.
