### ISSUE TITLE
scaladsl HttpMessage should use scaladsl HttpHeader

### ISSUE THREAD

**Issue by mzalewski82** [akka/akka-http#1304]
Now methods:
- getHeaders
- getHeader
- addHeaders
are using javadsl HttpHeader

**Comment by jrudolph** [comment]
Hi @mzalewski82, scaladsl and javadsl classes form a hierarchy, so that the scala version extends from the java version.

That means that `addHeaders` will accept the scala headers. `getHeaders` and `getHeader` are Java APIs explicitly. You would use `headers` and `header` in Scala.

Does that explain why things are the way they are?

**Comment by mzalewski82** [comment]
Thanks a lot @jrudolph now it's clear
