### ISSUE TITLE
Improve handling of UnknownHostException

### ISSUE THREAD

**Issue by EXPEylazzari** [akka/akka-http#1364]
Hi,

We're using Akka 2.5.4 and Akka HTTP 10.0.9 in production and ran into the following issue.

Consider the sample code:
```scala
val pool = Http().cachedHostConnectionPool[String](host = "potato")
val req = HttpRequest(method = GET, uri = Uri("/hello"))
val eventualResponse = Source.single((req, randomUUID().toString)).via(pool).runWith(Sink.head)
```
When the host does not exist, what you end up with is a failed `Future` whose error is a `StreamTcpException`. Below is the "complete" stack trace:

    akka.stream.StreamTcpException: Tcp command [Connect(potato:80,None,List(),Some(10 seconds),true)] failed because of potato

If find this a bit light on details. We winded up enabling debug logging in production and found a similar trace before the exception is thrown:

    [DEBUG] [08/17/2017 08:28:00.006] [Test-akka.actor.default-dispatcher-4] [akka://Test/system/IO-TCP/selectors/$a/5] Could not establish connection to [potato:80] due to java.net.UnknownHostException: potato

Only then did we clue in that the real problem was an intermittent DNS issue.

Would it be possible to improve error handling so that we're not forced to enable debug logging to find the real cause of such exceptions? Perhaps set the `UnknownHostException` as the cause of the `StreamTcpException` or improve the error message by incorporating the one from the `UnknownHostException` inside?

Not sure if the underlying problem is in akka-http or akka-stream, so I opened the issue in akka-http for now.

Thank you!

**Comment by jrudolph** [comment]
Thanks for the report, @EXPEylazzari. You are right this error is funny but not really helpful. The reason is that we seem to create the `UnknownHostException` with just the name and no more message here

https://github.com/akka/akka/blob/c2ff4f74fcc6de90cafdc1a8b21d2fe914c8d917/akka-actor/src/main/scala/akka/io/Dns.scala#L34

I created https://github.com/akka/akka/issues/23543 to track this in akka directly. Could you open PR with an improved message against akka/akka?
