### ISSUE TITLE
charset ignored for some mediatypes

### ISSUE THREAD

**Issue by rabbah** [akka/akka-http#1394]
In the following test, where the route creates a content type with a charset, the response drops the latter.

```scala
import org.scalatest._
import org.scalatest.Matchers
import akka.http.scaladsl.model._
import akka.http.scaladsl.server._
import akka.http.scaladsl.testkit.ScalatestRouteTest

class MissingCharSet extends WordSpecLike with Matchers with ScalatestRouteTest with Directives {

    val mt: MediaType = MediaTypes.`text/html`
    val data: String = "hello"
    val contentRoute: Route = {
        complete(HttpEntity(ContentType(MediaType.customWithFixedCharset(mt.mainType, mt.subType, HttpCharsets.`UTF-8`)), data))
    }

    "The contentRoute" should {
        "return HTTP content-type with character set" in {
            Get("/") ~> contentRoute ~> check {
                contentType shouldBe MediaTypes.`text/html`.withCharset(HttpCharsets.`UTF-8`)
            }
        }
    }
}
```

fails with
```
MissingCharSet:
The contentRoute
- should return HTTP content-type with character set *** FAILED ***
  text/html was not equal to text/html; charset=UTF-8 (MissingCharSet.scala:41)
```

Is this expected?

**Comment by jrudolph** [comment]
Hi @rabbah,

this is because you are circumventing our data types by creating a custom media type. The `WithFixedCharset` variant of a `MediaType` means that the charset is fixed in the specification (like UTF-8 for `application/json`). In that case, we suppress rendering the charset (because it is fixed anyway) which seems to be exactly the opposite of what you want to achieve.

Try 

```scala
ContentType(MediaTypes.`text/html`, HttpCharsets.`UTF-8`)
```

instead.

**Comment by jrudolph** [comment]
Closing for now. Please feel free to let me know if I'm missing something.

**Comment by rabbah** [comment]
Thanks - indeed after more source reading I found a more appropriate way of doing what I needed to.
