### ISSUE TITLE
Leaking open resources on high load requests 

### ISSUE THREAD

**Issue by 123avi** [akka/akka-http#1411]
Hi,
I tried to perform a simple test - 
I created a simple outgoing request in a loop simulating users raining 200k requests :
```
  def apiConnectionFlow: Flow[HttpRequest, HttpResponse, Any] =
    Http().outgoingConnection(host, port)
  def apiRequest(request: HttpRequest): Future[HttpResponse] = Source.single(request).via(apiConnectionFlow).runWith(Sink.head)
  val numRequests = 200000
  for (i <- 1 to numRequests){
    apiRequest(RequestBuilding.Put("/foo", Foo(i)))
  }
```
and a server that accepts this requests 
```
val routes: Route = logRequestResult("foo-service") {
    pathPrefix("foo") {
      pathEndOrSingleSlash {
        put {
          entity(as[Foo]) { foo =>
            complete{
              Future(foo).map(r => s"Update - $r ")
            }
          }
        }
      }
    }
  }
  Http().bindAndHandle(routes, "0.0.0.0", 9000)
```

how ever looking at the listeners using` lsof -i tcp:9000 | wc -l ` command I see that the number is constantly increasing (**more than 6000**!!!) it seams leaking from some point 
and eventually I am getting the following error

> [akka.actor.default-dispatcher-31] [akka://in-test/system/IO-TCP/selectors/$a/0] Accept error: could not accept new connection
> java.io.IOException: Too many open files in system
> 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
> 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
> 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
> 	at akka.io.TcpListener.acceptAllPending(TcpListener.scala:107)
> 	at akka.io.TcpListener$$anonfun$bound$1.applyOrElse(TcpListener.scala:82)
> 	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
> 	at akka.io.TcpListener.aroundReceive(TcpListener.scala:32)
> 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
> 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
> 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
> 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
> 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I also posted that on [akka user mailing list](https://groups.google.com/forum/#!topic/akka-user/XSTrFwgAA-k) 
what's going on ? is there a solution / workaround ?

**Comment by jrudolph** [comment]
Hi @123avi,

in which state are all those connections (remove `|wc -l` to see)? You seem trying to concurrently open 200000 connections. This puts a lot of pressure on the OS and is not a trivial thing to get right. What would you expect to see? What is the state after all the 200k connections have run through?

**Comment by satansk** [comment]
Hi @123avi , the exception is clear: Too many open files in system. It seems the process reached the max open file limit allowed by OS, and you can get the limit by `ulimit` -n on linux. Have a try~~

**Comment by 123avi** [comment]
@jrudolph , @satansk thanks for your comments. I understand that I am opening too many connections. but shouldn't they be closed after the request completed ? running smaller number of requests e.g 10K maintains a normal number 2~4 (`lsof -i tcp:9000 | wc -l`) so in 100k requests I would expect something like 20~40 open connections. but at some point this number is increasing rapidly and reaches above 7000.  is that make sense ?

**Comment by jrudolph** [comment]
@123avi as mentioned above, you need to check what state the connections are in. You claim that connections would be kept open after the request has been finished but just showing a number of connections is no evidence for that. If you look at the state you will probably see most connections being in the `SYN_SENT` state which means that the connections are not yet established. To be sure, don't execute client and server side on the same machine.

Again: if you open 200000k connection **at the same time** how many connections do you expect to be open or attempted at the same time? It could actually be 200k if nothing is throttling. Indeed, there will be some limiting factors:

 * requests will be processed and used connections will be get closed again
 * CPU usage will prevent too many connections from being opened concurrently
 * last and most importantly there's only a limited number of ephemeral ports. That means the number of concurrent connections from one host to another host/port is restricted by the number of available ports for the outgoing interface, which cannot be more than 2^16. In fact you usually cannot even get to this number because the OS will try to automatically allocate client-side ports from the range of ephemeral ports. If you exhaust ephemeral ports the behavior in Linux can become very weird with (otherwise asynchronous) socket `connect` calls start to [block while trying to allocate a new ephemeral port](https://www.spinics.net/lists/netdev/msg228132.html).

Can you

 * check what happens if you run client and server on different machines
 * check how many connections are actually left open (and not in `TIME_WAIT`) after the whole test has finished

**Comment by jrudolph** [comment]
Closing because of missing information. If this is still an issue, @123avi please let us know.
