### ISSUE TITLE
FAILED: nightly build against Akka 2.4

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1517]
I.e. https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/321/console

Probably because akka-http is now on sbt1, while akka 2.4 isn't.

I guess we'd like to test against published artifacts anyway instead of pulling in the akka 2.4 sources?

**Comment by jrudolph** [comment]
Yep binaries makes sense for testing against older releases.

**Comment by ktoso** [comment]
Makes quite some noise in emails on surface. Working on other surface things now, this would be good to solve tho..

**Comment by johanandren** [comment]
Wait a minute, http-nightly-against-akka-master isn't against Akka 2.4, it's against master, so that can't be the explanation here.

**Comment by johanandren** [comment]
This was fixed but the ticket left open?

**Comment by johanandren** [comment]
The tests has been running since december 18, seems like the HTTP2 test suite is failing a lot if not completely though.

**Comment by jrudolph** [comment]
This ticket was about a nightly job which I deleted when switching to Akka 2.5. Before we ran nightlies against the Akka release-2.4 branch *sources*. It was nice to have as long as it worked but for now we would hope that release-2.4 branch changes are seldom enough by now not to introduce incompatibilities not caught otherwise.

I'd suggest to close this ticket.

**Comment by johanandren** [comment]
Alrightey
