### ISSUE TITLE
Add caching get(K, V) overload to avoid function allocation

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1536]
We should add an overload that does not force the function here: 

`def get(key: K, block: () ⇒ V): Future[V] =`

Feedback via @ben-manes

Note that block is not GC friendly, since it requires allocating a capturing lambda for the key. This is a small overhead, but worth being aware of. The alternative, e.g. in Map#computeIfAbsent, is to pass a function k -> v so that the caller can opt into the lamda being cached by the JVM.

https://github.com/akka/akka-http/pull/1503#discussion_r152172802

**Comment by catalin-ursachi** [comment]
Just to check: if I understand @ben-manes's comment (https://github.com/akka/akka-http/pull/1503#discussion_r152173100) correctly, what he's suggesting is adding the methods:
```
def apply(key: K, genValue: K => Future[V]): Future[V] = ...

def get(key: K, genValue: K => V): Future[V] = ...
```
so that the caller can define the value-generating functions once and pass them in as a function argument, so that a new lambda needn't be defined for each function call.

E.g., allowing the following pattern
```
def createProfile(user: Id): Future[Profile] = ...

def getProfile(user: Id): Future[Profile] = cache.get(user, createProfile)
```
Is that correct? Should I go ahead and implement that?

Do you also want the methods:

```
def apply(key: K, value: Future[V]): Future[V] = ...

def get(key: K, value: V): Future[V] = ...
```
They seem of limited usefulness; and the `value` parameter could potentially be mistaken by the user for a 'pass-by-name' parameter (leading to unfortunate behaviour).

**Comment by ben-manes** [comment]
I think [JEP 210](http://openjdk.java.net/jeps/210) improved the JVM's caching of lambdas. I cannot find the details, but my understanding is that non-capturing lambdas (no non-static instance fields) are singletons. I think that capturing lambdas of class-scoped variables are cached with the instance, and method-scoped variables requires an allocation every time. So a hot code path would always allocate in the current API and the improvement would let the JVM transparently cache it.

But I could be wrong and its a micro optimization, so good API design comes first.

**Comment by catalin-ursachi** [comment]
So if I understand correctly:

```
foo(() => baz())
```
and
```
foo((bar) => baz(bar))
```
will be cached by the JVM, whereas:
```
foo(() => baz(bar))
```
will not?

**Comment by ben-manes** [comment]
Yes, if I am correct. It wasn't very good pre-JEP210, as I recall caching a lambda in Caffeine to avoid allocations when it was an instance method reference (after profiling). At the time I Google'd and found a JVM engineer say it was being worked on. But I can't find that, so I guess a JMH benchmark would be needed to verify.

**Comment by jrudolph** [comment]
Definitely makes sense to add these. Regardless of whether the JVM or scalac actually do cache the lambdas it will at least allow to cache them manually if required.
