### ISSUE TITLE
Fail fast on Akka version mismatch

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#1538]
When getting an older Akka version pulled into a project than what is supported by/works with Akka HTTP you get missing method errors etc but would be nice if we instead could check on load of the extension and fail fast with a nice error message saying "You have Akka 2.x.y in your class path but need at least Akka version 2.a.b".

**Comment by ktoso** [comment]
There's two main case:

- akka http is compiled against akka 2.4.X yet user uses Akka less than 2.4X (in sbt that would get evicted and the later version would win, though not so much in some cases in maven it seems)
  - then we want to fail hard I guess, since they run at the risk of blowing up in runtime due to internals requiring 2.4.X features
- akka http 10 being used with 2.4
  - just log a warning or suggestion that the user should upgrade akka and akka streams to 2.5.[latest], and link to the docs why this works

Once 10.1 is out the latter one becomes the first one.

This has to be implemented by putting a compile build time akka-version value in the 

```
package akka.http
object Version 
```

object (this already exists, just add the akka version in there too).

**Comment by johanandren** [comment]
Maybe we should even provide something from Akka core to make this easy for any library built with/on top of Akka?

**Comment by ktoso** [comment]
Hm, sounds fun actually. Since we have a number of satelite projects

**Comment by patriknw** [comment]
Ping. I think this is important for Akka HTTP 10.1.0 since dependencies are provided and now we have the utility in Akka.

**Comment by johanandren** [comment]
I'll PR this

**Comment by johanandren** [comment]
Not as straight forward as it seems. 

The version require utility was introduced in 2.5.10 which means that if we start using it, we do not in fact support `Akka HTTP 10.1.x is (binary) compatible with Akka 2.5.x` as the docs says, maybe this is fine and we should just change the docs, but I'm not sure, would like a second opinion here.

**Comment by patriknw** [comment]
We will never support all of 2.5.x all the way to 2.5.0, because sometimes we have to add things (e.g. in akka-stream) that are needed in akka-http. That's why we need to set a minimum supported version. For 10.1.0 I think it's fine to pick the latest and greatest 2.5.10. Later we will probably be conservative and only bump the minimum when really needed (or at least have some lag of a few patch versions).

**Comment by ktoso** [comment]
This was merged

**Comment by johanandren** [comment]
What's the PR it was merged in, because my PR was just closed.

**Comment by ktoso** [comment]
Oh :/ Sneezed my brain out today it seems
