### ISSUE TITLE
Underscore in @unidoc directive breaks rendering

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1648]
/cc @raboof

**Comment by raboof** [comment]
Example: `@unidoc[Flow[HttpRequest, HttpResponse, _]]` in introduction.md

Looks like this is because technically further markup is allowed inside the `[]`, and `_` is used to mark italics. In our case however unfortunately the typical solution of escaping the underscore does not work because our directive treats the part between `[]` as text, so the escape character is outputted as part of the link.

I think we should escape the underscore, and update the directive to interpret the escape character away.

**Comment by jrudolph** [comment]
Exactly, that's the example I found as well. I wonder if it is even worthwhile to fix or if we can replace the underscores in the stream cases by `Any` or `NotUsed`?

**Comment by raboof** [comment]
Or maybe we should replace `_` by `?` when generating Java versions?

**Comment by jrudolph** [comment]
Yep, could be a solution as well. We would still have to quote the underscores, right?

**Comment by raboof** [comment]
Yes - but I think that's OK, it would be weird to use markup syntax in some directives but not others, even though we don't do anything with it for unidoc.

**Comment by jrudolph** [comment]
Yes, I agree. If you understand what's going on I guess it's clear enough. Would be nice if you could customize parsing of directives to allow a "raw" mode that isn't markup syntax but I also understand that this wouldn't be easy to do.

**Comment by jrudolph** [comment]
Fixed by #1654.
