### ISSUE TITLE
10.0.11 doc searches give 10.1.0-RC2 results

### ISSUE THREAD

**Issue by pjfanning** [akka/akka-http#1855]
https://doc.akka.io/docs/akka-http/10.0.11/scala/http/index.html

I agree that searches on 10.0.x should return the latest 10.0 docs.
But I wonder if it's ok for 10.0.x searches to return 10.1 RC results.

**Comment by jrudolph** [comment]
Former discussion: https://github.com/akka/akka-http/issues/1587#issuecomment-364933136

Mostly due to technical reasons we decided to only index a single version of the documentation which is the `current` version of the docs.

I guess we could think about not making an RC the `current` version. Though, at this point the difference between versions are mostly for convenience, so most people will profit from reading the current documentation with the backside of a bit of confusion.

**Comment by jrudolph** [comment]
Has been de-facto fixed by releasing 10.1.0. We currently don't support searches for older versions.
