### ISSUE TITLE
Send 426 response if protocol isn't supported (HTTP <2)

### ISSUE THREAD

**Issue by richdougherty** [akka/akka-http#1992]
As mentioned in a related Play PR (https://github.com/playframework/playframework/pull/8357#issuecomment-380259722) we need to ensure that we have some sort of handling in place for HTTP 1.x requests. My suggestion would be to send a `426 Upgrade Required` response if we receive an HTTP 1.x request.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426

**Comment by richdougherty** [comment]
Closed because this is an akka-grpc issue! https://github.com/akka/akka-grpc/issues/180

**Comment by ktoso** [comment]
I think the ticket is valid in both places.
We want to have a "h2 only" mode, in which case akka-http itself would also be in position to reply with an 426

**Comment by raboof** [comment]
Hmm, I'm not completely sure. I'd say we want the following modes:
* Secure h2-only: speak h2-over-TLS immediately (regardless of ALPN negotiation, not yet supported, #1995)
* Secure negotiated: TLS, h2 when negotiated via ALPN (default behavior)
* Insecure h2-only: start speaking h2 immediately  (without Upgrade negotiation, will not work as an HTTP/1 server, supported since #1934)
* Insecure negotiated: start as HTTP/1, but switch to h2 with the Upgrade mechanism (not yet supported, #1966)

Do we really want to add a fifth variant, which is insecure and uses the `Upgrade` mechanism but replies with a `426` when the user attempts to use it without first upgrading?

**Comment by ktoso** [comment]
I had assumed the “only” mode would be nicer to reject insecure ones like this.
We can close and reopen in case someone requests it some day (or never)
