### ISSUE TITLE
upgrade provided akka dependency to Akka 2.5.12?

### ISSUE THREAD

**Issue by SethTisue** [akka/akka-http#2009]
2.5.12 has been out for a while, but akka-http is still on 2.5.11

(why do I care? I'm in the process of sorting out some Akka-related failures at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2859/consoleFull. haven't gotten to the bottom of it yet, but in general, it's helpful to have Lightbend projects using each other's latest versions, since the latest versions are usually also what I'm building in the community build so it reduces the probability of something going wrong and the number of possible causes to investigate when something does go wrong)

**Comment by SethTisue** [comment]
see also https://github.com/playframework/playframework/issues/8404

**Comment by ktoso** [comment]
Yeah, good point that we should update the dependency for the build.
For reference though, Akka is not an explicit dependency but a `provided` one since the recent releases as explained here https://akka.io/blog/news/2018/03/08/akka-http-10.1.0-released so for end-users it is up to them to pick an akka version; for your case and the dbuild infra that does not matter though since it is the tests, so absolutely agreed that we should update -- will do so right away and add to our release process to do so each time when we release
