### ISSUE TITLE
Support wildcard for Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2111]
Currently netty (https://github.com/netty/netty/issues/1374) has this option and is the default for play. 

Related play issues: https://github.com/playframework/playframework/issues/7943 and https://github.com/playframework/playframework/issues/7895

There's a discussion that play should offer an API for it but having a `*` has the default seems sensible for people migrating from netty to akka http as a backend for play/lagom.

**Comment by raboof** [comment]
The proposed change would be a workaround for the fact that some clients use the list of 'subprotocols' not to select a subprotocol, but to send metadata in the request. That would be fine, but apparently some client libraries check that the server selects one subprotocol from the list (it's not obvious from the spec that the server has to choose?), and this change makes the client happy by just arbitrarily returning one of the values.

I'd really prefer fixing this by having the 'downstream' implementation (i.e. Play) call `handleWebSocketMessagesForOptionalProtocol(handler, requestedProtocols.headOption)` instead of adding support for the current `handleWebSocketMessagesForProtocol(handler, "*")`. Or are there situations where that is not reasonable to expect?
