### ISSUE TITLE
decodeRequest does not respect withSizeLimit

### ISSUE THREAD

**Issue by tewe** [akka/akka-http#2137]
When using [decodeRequest](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/coding-directives/decodeRequest.html) to handle `Content-Encoding: gzip` any [withSizeLimit](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/misc-directives/withSizeLimit.html) applies to the compressed size, not the uncompressed size. This might facilitate DoS attacks.

The reason might be that `decodeRequestWith` uses `transformDataBytes` which creates a new `HttpEntity` that is not limitable.

**Comment by TheEmacsShibe** [comment]
I tested this and it can indeed crash a server. The following shell commands can create a large enough gzip file and send it to the server:

```
dd if=/dev/zero bs=1M count=6000 | pv | gzip -9 > foo.gz
curl -v -i http://example.com/post-endpoint -H'Content-Encoding: gzip' --data-binary @foo.gz
``

**Comment by jrudolph** [comment]
Thanks for the report. We'll look into it.

**Comment by jrudolph** [comment]
The idea used to be that by basing everything on streaming, these kind of issues are less likely. However, there are two main parts where streams are loaded into memory:

 * `toStrict` (in all variants)
 * `PredefinedFromEntityUnmarshallers.byteStringUnmarshaller` which blindly collects everything it gets and which is the base unmarshaller for basically all other strict unmarshallers like those used for the `formData` directive.

`toStrict` docs at least contain a warning that this might not be a good idea but for the unmarshallers it is unexpected.

I think we might want limits at different stages:

 * `withSizeLimit` / `max-content-length` as input limits
 * `decodeRequest` and everything that potentially inflates data
 * `toStrict` should have a limit
 * `PredefinedFromEntityUnmarshallers.byteStringUnmarshaller` and other marshallers that might collect data should have limits

I propose the following changes:
 * add config settings for each of those cases with a reasonable default limit (which isn't unlimited) like 10MB per request
 * change `decodeRequest` to add another stage which honors the limit
   * maybe add a variant of `decodeRequest` that allows to change limit as a shortcut
 * same for `toStrict` directives
 * limiting the unmarshallers is the hardest because they are static and currently allow no possibility for configuration. With a bit of fiddling we could change the internals to pass configuration when they are invoked. Adding limits to `decodeRequest` and `toStrict` would restrict the problem for now, so maybe changing the unmarshallers could be postponed.
 * Create a documentation page listing limits and explaining rationale.

**Comment by jrudolph** [comment]
@raboof wdyt?

**Comment by jrudolph** [comment]
The problem is somewhat that we might end up with a zoo of limits that might interact  in non-obvious or unforeseen ways. The good thing about the basic streaming nature of Akka HTTP is that it can efficiently handle any amount of data -- if it's consumed in a streaming fashion using backpressure.

Ideally, the only thing that would need to be limited would be consumers that aggregate data.

If we now introduce all those limits, we hinder well-written streaming use cases because they have to deactivate all those limits.

On the other hand, a web server is also always a battle field where "defense in depth" might be appropriate.

**Comment by jrudolph** [comment]
For the time being here's a workaround which can be used safely:

```scala
def safeDecodeRequest(maxBytes: Long): Directive0 =
  decodeRequest & mapRequest(_.mapEntity {
    // decodeRequest will create chunked entity when it decodes something.
    // This adds the missing limit support.
    case c: HttpEntity.Chunked ⇒ c.copy(chunks = HttpEntity.limitableChunkSource(c.chunks))
    case e                     ⇒ e
  }) & withSizeLimit(maxBytes)
```

**Comment by jrudolph** [comment]
Safe workarounds for Java and Scala here:

https://gist.github.com/jrudolph/2be2e6fcde5f7f395b1dacdb6b70baf7

**Comment by jrudolph** [comment]
We are currently working on these solutions:

 * [ ] #2185 Make `HttpEntity.withSizeLimit` work in all cases and apply an extra limit to `decodeRequest`
 * [ ] #268 / #2186 Allow specifying a maximum size for `toStrict` (or apply a default limit)
