### ISSUE TITLE
Doesn't support chunked HTTP/2 responses

### ISSUE THREAD

**Issue by ctoomey** [akka/akka-http#2217]
Chunked HTTP/2 responses are disallowed, and shouldn't be, by the following check in `akka.http.scaladsl.model.HttpResponse`:
```
  require(
    protocol == HttpProtocols.`HTTP/1.1` || !entity.isInstanceOf[HttpEntity.Chunked],
    "HTTP/1.0 responses must not have a chunked entity")
```
The check should instead be 
```
protocol != HttpProtocols.`HTTP/1.0` || !entity.isInstanceOf[HttpEntity.Chunked]
```

**Comment by jrudolph** [comment]
The reasoning is that akka-http2-support can actually handle `HttpEntity.Chunked` by ignoring the chunk extensions but supporting the trailers using the usual HTTP/2 stream framing.

We already [make use](https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/internal/GrpcResponseHelpers.scala#L56) of this feature in akka-grpc.

Why does it work there? Because for outgoing responses, akka-http doesn't require that the `protocol` of a response is set correctly (the protocol field is just ignored).

So, as long as you don't set the protocol of a response to HTTP/2 you can already now use `Chunked` with HTTP/2.

**Comment by ctoomey** [comment]
I needed it to work w/ HTTP/2 protocol as part of an alternate Play integration I'll be proposing separately that involves returning `EssentialAction`s so that Play's `Filter` chaining support can be leveraged like usual. So the `HttpResponse` generation from the `Result` is handled downstream by Play's `AkkaHttpServer` and it copies the protocol from the request to the response.

**Comment by jrudolph** [comment]
Makes sense, thanks for providing the context, @ctoomey.
