### ISSUE TITLE
Make Akka dependency provided for the akka-http-testkit project

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#2262]
Currently, all main akka-http projects have a provided dependency with the Akka library. This is true for all projects except for the `akka-http-testkit` one.
The implication of this is that, if only the `akka-http-testkit` dependency is added, and not the `akka-streams-testkit` one, the akka version checker will fail and complain about different versions.

**Comment by jrudolph** [comment]
I wonder if that was by purpose because we don't really care that much for the testkit because it will be used only in tests where we don't expect any dependency problems (which was the reason to make it `provided` otherwise). On the other hand, it shouldn't matter, so maybe we can mark it provided there as well.

**Comment by jlprat** [comment]
I will take this one. I think is better to also mark it as provided for the sake of consistency.

**Comment by jrudolph** [comment]
Fixed by #2263.
