### ISSUE TITLE
Redirect to url with `=` in path

### ISSUE THREAD

**Issue by devenv** [akka/akka-http#2297]
Our use case:
User asks for a file on our server, we redirect him to a file on s3.
The problem is that s3 url has `=`s in it's path: e.g. `s3://bucket/date=2018-11-01?type=test` which is translated (and escaped) by s3client to `https://bucket.s3.amazonaws.com/date%3D2018-11-01?type=test&token=etc`.
When passed to `header.Location` it gets unescaped back to `date=2018-11-01`, which doesn't work.
AFAIK `=` is not allowed in the path part.
Using RawHeaders works.
akka version: 2.5.15
akka http version: 10.0.10

**Comment by jrudolph** [comment]
Thanks for the report and the workaround, @devenv. Yes, it's basically a known issue that AWS/S3 doesn't always follow the URI specification (which mandates which URIs should be treated as equal). Using a `RawHeader` is indeed the way to go for these kinds of third-party issues.

I'm closing this as "Won't fix" because there's a workaround and there's little we can do.

If you have an idea what behavior to change, please feel free to request reopening this issue.
