### ISSUE TITLE
Model HTTP/2 frame events

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#245]
Part of #244 

Frame types of the HTTP/2 specification should be modeled as case classes.

These events have or should been defined:
- [x] DataFrame
- [x] HeadersFrame
- [x] PriorityFrame https://github.com/akka/akka-http/pull/515#issuecomment-261204895
- [x] RstStreamFrame
- [x] SettingsFrame and SettingsAckFrame
- [x] PushPromiseFrame
- [x] PingFrame
- [x] GoAwayFrame https://github.com/akka/akka-http/pull/528
- [x] WindowUpdateFrame 
- [x] ContinuationFrame

**Comment by ktoso** [comment]
Adding the remaining models should be rather simple - feel free to help us out on these.

**Comment by gosubpl** [comment]
@ktoso @jrudolph is that still valid? If yes, I'd like to take on PriorityFrame. Will that be ok?

**Comment by ktoso** [comment]
Absolutely, please hack away :-)

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 25 October 2016 at 14:14:06, gosubpl (notifications@github.com) wrote:

@ktoso <https://github.com/ktoso> @jrudolph <https://github.com/jrudolph>
is that still valid? If yes, I'd like to take on PriorityFrame. Will that
be ok?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/245#issuecomment-256017837>, or mute
the thread

**Comment by ktoso** [comment]
Go away worked on by @schmitch here https://github.com/akka/akka-http/pull/528

**Comment by jrudolph** [comment]
Support for the last one (`PUSH_PROMISE`) was added in 3ab873a.
