### ISSUE TITLE
Switch to Scalafmt

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#2508]
After Akka switching to Scalafmt, maybe Akka HTTP should follow suit and also use Scalafmt.

Additionally, we should also replace unicode arrows with the multi-character equivalent: `⇒`, `→`, `←` to `=>`, `->`, `<-`

**Comment by jrudolph** [comment]
I'm not super keen to do that too early. In akka, just checking the formatting currently takes > 10 minutes for every PR validation build. Of course, there's much less code in here but as long that's not improved to more reasonable values, I don't see us changing here as well.

**Comment by jlprat** [comment]
What about the unicode arrows? Should we proceed with this? If so, I could create another ticket to track only that change.

**Comment by jrudolph** [comment]
Unicode arrows are gone with https://github.com/akka/akka-http/pull/2531.

**Comment by dwijnand** [comment]
> just checking the formatting currently takes > 10 minutes for every PR validation build

Is this concern resolved with https://github.com/scalameta/sbt-scalafmt/issues/25 now fixed?

**Comment by jrudolph** [comment]
> Is this concern resolved with [scalameta/sbt-scalafmt#25](https://github.com/scalameta/sbt-scalafmt/issues/25) now fixed?

It's better but not still much slower than with scalariform.

**Comment by jrudolph** [comment]
I'm going to close this for now. With the comma and unicode arrow fix in the latest scalariform there seems to be much less pressure to change to anything else.

**Comment by ignasi35** [comment]
It's been almost a year since the last activity here. Any chance we can revisit this decision?

Scalariform has been dormant for these past 12 months while scalafmt remains active. 

I've just tried `time scalafmt` on the root of the project (I used the scalafmt CLI, not the `sbt-scalafmt` plugin):

```
$ time scalafmt
... ## some warning and error omitted (it's edge cases we would need to tune)
scalafmt  93.80s user 2.79s system 1026% cpu 9.406 total
```

Running `scalariformFormat` takes: 

```
akka-http-root > scalariformFormat
[info] Formatting 15 Scala sources ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-http-testkit")(compile) ...
[info] Formatting 2 Scala sources ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-http-spray-json")(compile) ...
[info] Formatting 11 Scala sources ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-http-caching")(compile) ...
[info] Formatting 1 Scala source ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-http-xml")(compile) ...
[info] Formatting 20 Scala sources ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-parsing")(compile) ...
[info] Formatting 30 Scala sources ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-http2-support")(compile) ...
[info] Formatting 126 Scala sources ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-http")(compile) ...
[info] Formatting 175 Scala sources ProjectRef(uri("file:/Users/ignasi/git/github/akka/akka-http/master/"), "akka-http-core")(compile) ...
[success] Total time: 3 s, completed Jul 24, 2020 10:51:57 AM
akka-http-root >
```

The comparison is unfair considering the code is already formatted using scalariform and I run `scalafmt` using a native-compiled CLI, but the results are on the same ballpark (as of this writing).

Considering `scalafmt` is bundled in the scala tooling for IntelliJ, it is provided as a CLI, can be set up to _not_ run on every invocation to `compile`, and that is has become the _de facto_ standard in alsmost (if not all) other projects in the Akka ecosystem, we could re-think this issue.
