### ISSUE TITLE
Configurable HTTP/2 ping support

### ISSUE THREAD

**Issue by jroper** [akka/akka-http#2640]
It'd be great if Akka HTTP provided configurable HTTP/2 ping support, to ensure liveness of connections. This is particularly useful when streaming in gRPC, in cases where a streamed gRPC call may still be alive, but there just haven't been any events in either direction, so that that case can be distinguished from a dropped connection.

Technically, the configured idle timeout should probably not consider pings, though in many cases where pings are enabled, idle timeout would be disable because it doesn't make sense. What might make sense as an alternative is a timeout for when there are no active requests on the connection (or, a stream idle timeout for no active requests in the stream, and a connection idle timeout that's triggered when there's no streams).

**Comment by jrudolph** [comment]
Thanks, James, that looks like a useful addition. Maybe we can take some inspiration from the existing ping support for WebSockets.

**Comment by jrudolph** [comment]
https://github.com/grpc/grpc/blob/master/doc/keepalive.md has some ideas for how ping support could be structured:

 * only send PINGs when streams are open (otherwise fall back to idle-timeout)
 * restrict time / number of pings to send if no data is sent at all for a longer period
 * monitor incoming pings and close connection on overly frequent usages of pings

We should take those with a grain of salt and check whether they make sense for more general usage (especially being overly strict on incoming PINGs probably doesn't make sense if you don't control both client and server).

**Comment by jrudolph** [comment]
Done in #3617.
