### ISSUE TITLE
EntityStreamSizeException message is too specific about the cause of the problem

### ISSUE THREAD

**Issue by ppiotrow** [akka/akka-http#2741]
```
Response body: The request content was malformed:
EntityStreamSizeException: actual entity size (None) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream
```
This has happened to me on client side whenever the requests to a server was too big.
I tried to fix mentioned configuration on the server but it has never worked. I even suspected that my `application.conf` is not overriding the reference server configuration.
I've spend too much time trying to fix this issue.

It appeared that the issue is elsewhere. As I'm GZIP'ing the requests on the client side and server is successfully decoding them, the other parameter is used.
The responsible one is `akka.http.routing.decode-max-size` parameter. 
I think the message in the error code should point to this parameter in case `decodeRequest` is used. Also if possible `None` should be replaced with actual number.

**Comment by jrudolph** [comment]
Thanks for the report @ppiotrow. Just to be sure I understand correctly, you are getting this error message because the `akka.http.routing.decode-max-size` is set too low on the server side?

That seems to be true indeed. `EntityStreamSizeException` is used for any kind of limit that was set using `withSizeLimit` not just the configured ones.

We should change the error message in that regard. An easy solution would be to adapt the message not to include the misleading information (but that might still keep the user in the dark). A more comprehensive solution could be to add a `hint` parameter to the size limiting functionality that could be used to give more information to the user from the places where the limit is set.

**Comment by ppiotrow** [comment]
There are two client scenarios:

1. Sending plain text json with size over default 8m.
This works on server with respect to `akka.http.server.parsing.max-content-length` with clear error messages
2. Sending gzip'ed json with (uncompressed?) size over default 8m.
This breaks on server with error message pointing client to irrelevant configuration parameter.
Modifying `akka.http.server.parsing.max-content-length` makes no effect. You also wonder why `None` is calculated as entity size. Once you found `akka.http.routing.decode-max-size` parameter it fixes your use case.

**Comment by jrudolph** [comment]
Thanks for the clarification. I agree that it is misleading. It has evolved like this for historical reasons. This error message used to be emitted only for the given cause but since then the size limiting feature has been used in other places without making sure the reported error is still accurate.

**Comment by raboof** [comment]
I started down the path of providing specific hints, but doing that in a binary compatible way got rather hairy (e.g. would require new `withSizeLimit` methods in many places, and either introducing an additional exception or making `EntityStreamSizeException` no longer a case class), so I figured it was not worth it and tried to improve the wording of the generic message instead.
