### ISSUE TITLE
ChildRestartStats consumes too much memory and leads to OutOfMemory at last.

### ISSUE THREAD

**Issue by jilen** [akka/akka-http#2848]
Version: 10.1.10
![Screenshot from 2019-12-03 10-46-13](https://user-images.githubusercontent.com/546573/70016031-2e1d6480-15ba-11ea-92b4-82cfda387707.png)

After several days my server goes OutOfMemory. 
Note, that I am using akka-http as http client.

**Comment by jrudolph** [comment]
Can you upload a memory dump somewhere and send us a link?

**Comment by jrudolph** [comment]
Why do you think it is related to akka-http (and not just Akka)?

**Comment by jilen** [comment]
Because this appears after I replace `AsyncHttpClient`  with `akka-http-client`. Through I am not 100% sure. But it seems caused by auto retries. I've send the dump link via gmail.

**Comment by jrudolph** [comment]
Thanks, I got the dump. To set expectations I'm now on vacation so it might be a while until I can look into it.

**Comment by johanandren** [comment]
Feels like it possibly could be related to akka/akka#27948

**Comment by jrudolph** [comment]
@jilen, seems like you are creating lots of `ActorMaterializer` without shutting them down after use. The best practice is to only create one instance of `ActorMaterializer` and pass that around. Once you upgrade to Akka 2.6.x, this won't be a concern any more because you don't have to create a materializer yourself any more and can just pass in the actorsystem instead.

**Comment by jilen** [comment]
@jrudolph  Exactly! Thanks for your help.
