### ISSUE TITLE
akka-http: scaladsl.model.Uri.toString doesn't encode query string

### ISSUE THREAD

**Issue by sampathsree** [akka/akka-http#3024]
Strict Parsing
```
scala> val uri = Uri("https://akka.io/test/?y=i%20dont%20know", mode=Uri.ParsingMode.Strict)
uri: akka.http.scaladsl.model.Uri = https://akka.io/test/?y=i%20dont%20know

scala> uri.toString
res3: String = https://akka.io/test/?y=i%20dont%20know

scala> uri.query(mode = Uri.ParsingMode.Strict).toString()
res4: String = y=i+dont+know
```

Relaxed Parsing
```
scala> val splUri = Uri("https://akka.io/test/?y=i%20dont%20know[]", mode=Uri.ParsingMode.Relaxed)
splUri: akka.http.scaladsl.model.Uri = https://akka.io/test/?y=i%20dont%20know[]

scala> splUri.toString
res9: String = https://akka.io/test/?y=i%20dont%20know[]

scala> splUri.query(mode = Uri.ParsingMode.Relaxed).toString()
res10: String = y=i+dont+know%5B%5D
```

**Comment by jrudolph** [comment]
Thanks for the report, @sampathsree. That seems at least inconsistent between strict and relaxed mode.

What you get from `query()` is a parsed model of the query string so it will interpret percent encodings and split parameters etc. The question is how `toString` should behave.

@raboof since you've been there recently, could you look into that?

**Comment by raboof** [comment]
I think this is intended behavior, unless I am missing something.

It is correct that `Query` applies some normalization/interpretation to the query string that are not performed by `Uri`. This is because `Query` implements the convention of encoding key=value pairs in the query string. This convention is common, but it's not generally the only possible interpretation of query strings in URI's.

For that reason, `Uri` leaves the query string relatively untouched (except for, in relaxed mode, percent-encoding characters that are not valid there, such as the `[]` in your example). It's only when parsing the query string into a key-value `Query` that the further normalizations are applied, such as in your example converting the percent-encoded spaces (`%20`) into equally-valid `+` characters.

Since `%20` and `+` are both valid encodings of the 'space' character, we might be tempted to turn `%20` into `+` already in the `Uri` query string. While that's unlikely to be problematic in practice, in theory it could be. You can compare this to `=` and `%3D`, which are both valid encodings of the `=` sign, but `i%3Ddont=know` and `i=dont%3Dknow` are definitely interpreted differently, so it would be premature to convert them in `Uri`. For that reason I think it's reasonable to leave it untouched in `Query`.

Does that explain things @sampathsree ? Are there situations where this leads to problems for you?

**Comment by jrudolph** [comment]
Ah, I missed that this is about `+` / `%20`, so it's consistent between strict and relaxed, so that `toString` will/should always return a safe string to include in a URI. Basically what it did was canonicalizing the representation.

**Comment by sampathsree** [comment]
Thank you @raboof  & @jrudolph. Your explanation makes sense why we want this behavior with query strings. The reason I raise this issue is because I was trying to use `Uri.normalize` to normalize the url strings into RFC-3986 format in Strict mode. After quite a bit of testing found out that Uri.toString is skipping encoding for query strings in `renderUriWithoutFragment` method. I was wondering was this intentional or a bug. I just noticed some new changes via #3003, Which makes a lot of sense. I will update my code to validate/encode query explicitly rather than relying on `normalize` for now, as I am using `10.1.10` Thanks for quick and clear response.

**Comment by raboof** [comment]
No problem! Feel free to get in touch if you have any further thoughts on the behaviour in 10.2!
