### ISSUE TITLE
Deprecate `HttpApp`

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#3155]
The `HttpApp` which is marked `@ApiMayChange` would need to be adapted for use with the new actor APIs and Coordinated shutdown.

Instead of working on that, the examples for a simple server application should be improved and `HttpApp` deprecated.

See #960, #1741, #1300, #1460

**Comment by jlprat** [comment]
Sad to see `HttpApp` go

**Comment by ennru** [comment]
I agree it is nice for simple things, but it doesn't scale well.

**Comment by ennru** [comment]
I guess one answer could be to link to https://developer.lightbend.com/guides/akka-http-quickstart-scala/ and https://developer.lightbend.com/guides/akka-http-quickstart-java/

**Comment by jrudolph** [comment]
> Sad to see `HttpApp` go

Quite understable! Just to give a bit more of a background on that decision: HttpApp works best if you have an application that centered around akka-http routes (which is a perfectly valid use case, if you ask me). As soon, as you use other pieces of akka, you need some bootstrapping code anyway. In this case, `HttpApp` can get in the way because it tries to "manage" the ActorSystem for you. This is even more pronounced with the new akka typed APIs that recommend a bit different way of structuring/wrapping HTTP boot code, where the subclass-based style of HttpApp is not quite fitting.

The goal should be that bootstrapping an akka-http server alone is almost as simple as using HttpApp but does not hide creating the ActorSystem, so it is easy to expand that initial bootstrap code into an Akka application that uses more of Akka's features. That also goes the other way, where you start with an Akka application and add akka-http routes. Adding the server shouldn't be more than adding one extra line to your existing bootstrap code.

The feature we lose with HttpApp, is shutting down the ActorSystem by default when pressing ENTER. It seems that feature is mostly useful during testing. For that, I'd recommend to use sbt-revolver instead.

**Comment by ennru** [comment]
Fixed with #3162.
