### ISSUE TITLE
how can i get the  bytestring of  the  post request？ 

### ISSUE THREAD

**Issue by Lovecxgood** [akka/akka-http#3441]
hi~
I meet a problem of using akkahttp 
how can I get the body  data  of a post request!
i have read your official document, but it is too simple to find a post request sample!
i have get the code of below,but i dont know how to get the  bytestring data
thank you!

Source<ByteString, Object> bytes = request.entity().getDataBytes();

**Comment by raboof** [comment]
We use the issue tracker for bugs/feature requests, so this question would fit better on stackoverflow or https://discuss.akka.io.

That said, you can use `toStrict` as documented at https://doc.akka.io/docs/akka-http/current/implications-of-streaming-http-entity.html: `request.entity().toStrict(...).getData()`.

This does mean you'll read the whole entity in memory - if you want to avoid that then you'll have to process it in a streaming way instead of using 'toStrict'.

**Comment by raboof** [comment]
(added https://github.com/akka/akka-http/pull/3446 to show this in the documentation)
