### ISSUE TITLE
Graceful shutdown for HTTP/2 servers

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3580]
Graceful shutdown is currently only enabled for HTTP/1.1 servers. A potential strategy for HTTP/2 servers could look like this:

 * immediately send MAX_CONCURRENT_STREAMS = 0 to notify client that no new streams are accepted
 * refuse incoming streams in the meantime
 * during a grace period wait for running requests to be completed
 * afterwards close connection with a GOAWAY

All this functionality could be enabled with a setting and implemented in the demux when the user request stream is cancelled (with Akka 2.6 we could use cancellation causes to distinguish between graceful and hard shutdown dynamically).

**Comment by benjamingeer** [comment]
Hi, we're trying to get Akka coordinated shutdown to work with cluster sharding and an Akka gRPC server. We're following the [example in the Akka HTTP docs](https://doc.akka.io/docs/akka-http/current/server-side/graceful-termination.html#akka-coordinated-shutdown) to add the recommended sequence to Akka’s coordinated shutdown. But when a cluster node starts to shut down, our gRPC service gets `java.util.concurrent.TimeoutException` errors waiting for actors to reply to `ask` requests, there are errors from the actor system like `[Recipient[Actor[...]] had already been terminated`, and a lot of dead letters are encountered. We expected the gRPC service to finish processing pending requests and stop accepting new ones before actors are terminated, but It looks like it's continuing to try to contact actors after they've already been terminated. Could this be because gRPC uses HTTP/2, and Akka HTTP doesn't yet support graceful shutdown for HTTP/2 servers?

**Comment by jrudolph** [comment]
Yes, that seems likely.
