### ISSUE TITLE
URI validation causing program to hang

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka-http#3646]
I encountered a confusing behavior of `Uri.apply` with Akka HTTP 0.10.1. 

For details please see https://discuss.lightbend.com/t/testing-akka-http-0-10-1-host-level-client-side-api-in-an-actor-with-scalatestwithactortestkit/7526/7?u=zhenhao

My observation could be wrong though. Please correct me if that's the case.

**Comment by raboof** [comment]
As discussed in https://discuss.lightbend.com/t/testing-akka-http-0-10-1-host-level-client-side-api-in-an-actor-with-scalatestwithactortestkit/7526/7 , I suspect `Uri.apply` threw an exception here: because 'http://' was missing the hostname was interpreted as the scheme, and some characters (like `%`) are allowed in the hostname but not the scheme, leading to an exception when you introduce them here.

Why that exception was not logged is something to analyze further, but it seems the URI validation itself is fine - so I'll close this particular issue for now (though of course further analysis could lead to opening another issue ;) )
