### ISSUE TITLE
Requests with closed upstreams are not handled with `max-connections`

### ISSUE THREAD

**Issue by 2m** [akka/akka-http#368]
Reproducer [here](https://github.com/svezfaz/akka-http-proxy-example)

The problem is that when `max-connections` is set to a lower value than gatling load test opens connections, some incoming connections are buffered in the OS kernel throughout all of the test. When the test finishes, these buffered connections are closed by gatling, but akka-http server still handles them  without respecting `max-connections` setting.

**Comment by jrudolph** [comment]
Ok, the reason is probably that in `Http.bindAndHandle`, connteions are limited by the `watchTermination` future and termination is monitored on the upstream so that completion may be handled concurrently with a request still running. A simple solution could be to move the `watchTermination` behind the user handler  flow so that the user can decide when a connection should be closed (or be counted as closed wrt the maxConnection limit).

**Comment by 2m** [comment]
Exactly. Moving `watchTermination` solves this issue. The hard part was writing the actual test for it. I have a working gatling simulation running in `akka-http-tests` subproject that actually tests this. I was not able to reproduce the same behaviour with akka-http client though.
