### ISSUE TITLE
Akka 2.6.18

### ISSUE THREAD

**Issue by ahjohannessen** [akka/akka-http#3975]
Any chance to get a minor version bump that depends on Akka 2.6.18? Reason for asking is that Akka 2.6.18 is published for Scala 3. A bump would make it possible for libs that depend on Akka to be used in Scala 2 and 3 without Akka complaining about version mismatches.

**Comment by raboof** [comment]
You should be able to 'pull up' all Akka versions to 2.6.18 in your build without needing changes to Akka HTTP.

I'm not sure that would help though: since Akka HTTP is not available for Scala 3 yet (#3901), you would have to have a `for3Use2.13` dependency on Akka HTTP, but that would also pull in the 2.13 artifact of Akka. 

Having both the Scala 2.13 and the Scala 3 version of Akka on the same classpath seems like that wouldn't go well, so if you want to Akka HTTP in a Scala3 project you'd probably be best off using `for3Use2_13` for both the Akka HTTP and the Akka dependencies.

**Comment by ahjohannessen** [comment]
>since Akka HTTP is not available for Scala 3 yet

I know that, but I have libs that depend on Akka Persistence, and those libs are used by apps that use Play and apps that only use Akka, so I can upgrade some of my apps to Scala 3 and others have to stay on 2.13.x until akka-http and play support Scala 3.

Akka complains about version mismatches.

**Comment by raboof** [comment]
> Akka complains about version mismatches

You should be able to fix this by specifying the Akka dependency version in your project explicitly, that should override any lower Akka versions coming in transitively via Akka HTTP or Play. https://doc.akka.io/docs/akka/current/project/downstream-upgrade-strategy.html

**Comment by ahjohannessen** [comment]
@raboof I'll try that approach, thanks for the link :)

**Comment by raboof** [comment]
Did this work out?

**Comment by ahjohannessen** [comment]
Yep, but Play is updated with Akka 2.6.18 now :)
