### ISSUE TITLE
Tune benchmark of the web techempower benchmark?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka-http#4084]
The result is just relased 
https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=composite
https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext

https://www.techempower.com/benchmarks/#section=data-r20&hw=cl&test=composite

environment： https://www.techempower.com/benchmarks/#section=environment

**Comment by hepin1989** [comment]
Saw the pr ,cool。
https://github.com/TechEmpower/FrameworkBenchmarks/pull/7244

**Comment by jrudolph** [comment]
Don't expect wonders, though. ;) This was just a set of config improvements I had lying around.

**Comment by jrudolph** [comment]
plaintext went up from ~ 1,2M to 3M which makes sense given the optimizations:

https://www.techempower.com/benchmarks/#section=test&runid=1ac5aadd-2446-47dd-a411-408ed3e3028d&hw=ph&test=plaintext&l=zijbpb-sd&a=2

Non-pipelined json test is still somewhat slow (at 0.25x of fastest Scala impl colossus). Some reasons are:

 * still uses routing layer (compared to other frameworks and plaintext)
 * TCP infra setup is not optimal (extra hop between Akka IO and Akka streams costs a lot, I have some wip with a native streams TCP layer, that will already help quite a bit)
 * header and target url parsing could still be optimized
 * streams infra is somewhat costly (when all the other things are optimized), this will be hard to optimize for the general case (we see method dispatch cost in the interpreter and cost of passing data caused by `push`, `onPush`, `grab` call chains and chasing reference)
