### ISSUE TITLE
Content-Type header disappears with custom content type value

### ISSUE THREAD

**Issue by Vadi** [akka/akka-http#422]
Given I've a route like this -- 
```
path("sid" / IntNumber) { id =>
    post { ctx =>
      ctx.complete(ctx.request.headers.mkString(","))
    }
}
```
When I execute -
```
> curl -H "Content-Type: application/json" -d'{}' -XPOST http://0.0.0.0:8080/sid/123
```
It returns -
```
Host: 0.0.0.0:8080,User-Agent: curl/7.49.1,Accept: */*,Timeout-Access: <function1>%
```
Notice that `Content-Type` header is not returned. However, check this request &mdash;
```
curl -H "Blah: Blue" -H "Content-Type: moon" -d'{}' -XPOST http://0.0.0.0:8080/deployment/123
```
This one returns `content-type: moon` as expected.
```
Host: 0.0.0.0:8080,User-Agent: curl/7.49.1,Accept: */*,Blah: Blue,content-type: moon,Timeout-Access: <function1>%
```

Not sure what the issue is -- How content type value is disappearing when a valid value is sent out. I am using `headerValueByName` directive to implement a custom content type.

**Comment by Vadi** [comment]
Moved from https://github.com/akka/akka/issues/21702

**Comment by jrudolph** [comment]
Some headers are handled specially by Akka HTTP, see http://doc.akka.io/docs/akka/2.4/scala/http/common/http-model.html#HTTP_Headers.

The content-type of a request is in our model associated with the entity of the request. To access it use

```scala
request.entity.contentType
```

The reason that it seems to work for `Content-Type: moon` is that this is not a valid content-type header at all because `moon` is not a media-type.

See the grammar of a media-type in https://tools.ietf.org/html/rfc7231#section-3.1.1.1:

```
     media-type = type "/" subtype *( OWS ";" OWS parameter )
     type       = token
     subtype    = token
```

Headers that cannot be parsed are added to the `headers` list as a `RawHeader` to allow custom processing also for erroneous headers. That's why you are seeing it then.

Hope this explains it. Closing as invalid for now. Feel free to reopen if needed.
