### ISSUE TITLE
3.0.0-RC1 throughput seems to be low

### ISSUE THREAD

**Issue by derekwyatt** [akka/akka-http#426]
My server "used to" run about 14k request / second.  After installing the `3.0.0-RC1` build I am down to around 3k requests / sec.

The test was to run `wrk -d30 -t32 -c32 <url>`.

I'm sorry that I don't have any real comparisons... this is just something "I noticed".

**Comment by ktoso** [comment]
"used to" on 2.4.11 right?

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 24 October 2016 at 22:11:06, Derek Wyatt (notifications@github.com)
wrote:

My server "used to" run about 14k request / second. After installing the
3.0.0-RC1 build I am down to around 3k requests / sec.

The test was to run wrk -d30 -t32 -c32 <url>.

I'm sorry that I don't have any real comparisons... this is just something
"I noticed".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/426>, or mute the thread

**Comment by derekwyatt** [comment]
Yes, I believe so.  Honestly, though, @ktoso I wouldn't spend too much time on it.  I'm not exactly in a "clean room", right now... I've ripped my code up eight ways from Sunday tracking down some stability issues.  I almost feel bad about filing this issue at all.

But if you happen to have a bench you can run it on, verification that there isn't a throughput reduction would be great to see.

**Comment by derekwyatt** [comment]
I just saw a rate at 19k/sec. My results shouldn't be looked at.

**Comment by ktoso** [comment]
The regression testing infra is back (for this new repo): https://jenkins.akka.io:8498/view/Performance/job/akka-http-perf/

I don't see any real changes since the 16th which still had real date (before the move, then it was broken for some days). Seems it wasn't Akka itself.

I'll strike out the RPS number in the first comment so people don't panic :)
Thanks for keeping at it and updating the respective issues!

**Comment by ktoso** [comment]
I just revived our regression testing (was not ported to new repo) today,
we'll see soon tonight if there was a regression.

**Comment by derekwyatt** [comment]
Thanks for being so diligent.
