### ISSUE TITLE
Publish Scala API documentation on akka.io

### ISSUE THREAD

**Issue by callicles** [akka/akka-http#469]
Hi!

I can't find the documentation on akka.io.
Is it published? Am I looking at the wrong place?

Thank you,

**Comment by ktoso** [comment]
You mean the ScalaDocs? 
Akka HTTP is in the middle of moving into it's own repository etc, along with docs, which is why it's not part of Akka 2.4.12 anymore.
It was part of 2.4.11 however, so the docs are available here: http://doc.akka.io/api/akka/2.4.11/

Very very soon they will be under http://doc.akka.io/api/akka-http/current
