### ISSUE TITLE
`Server` string is still `akka-http/2.4.12`

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#500]
```
# curl -v http://localhost:8080

* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server akka-http/2.4.12 is not blacklisted
< Server: akka-http/2.4.12
< Date: Wed, 09 Nov 2016 10:56:04 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 11
< 
* Connection #0 to host localhost left intact
Hello world%  
```

**Comment by jrudolph** [comment]
Tested with 10.0.0-RC2

**Comment by ktoso** [comment]
Ah...! Good catch... Since we don't have our previous release script which
changed those things I think.
I can work on this and the other 2 build things in my morning in addition
to the entity btw.

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 9 November 2016 at 02:57:35, Johannes Rudolph (notifications@github.com)
wrote:

Tested with 10.0.0-RC2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/500#issuecomment-259387562>, or mute
the thread
