### ISSUE TITLE
Java DSL: Cannot get properly typed `UpgradeToWebSocket`  header

### ISSUE THREAD

**Issue by QmQvl** [akka/akka-http#507]
Trying to use `request.getHeader(UpgradeToWebSocket.class)` results in a compilation error:

```
TestWS.java:34: error: no suitable method found for getHeader(Class<UpgradeToWebSocket>)
        final Optional<UpgradeToWebSocket> wsHeader = request.getHeader(UpgradeToWebSocket.class);
                                                             ^
    method HttpMessage.getHeader(String) is not applicable
      (argument mismatch; Class<UpgradeToWebSocket> cannot be converted to String)
    method HttpMessage.<T>getHeader(Class<T>) is not applicable
      (inference variable T has incompatible bounds
        equality constraints: UpgradeToWebSocket
        upper bounds: HttpHeader)
  where T is a type-variable:
    T extends HttpHeader declared in method <T>getHeader(Class<T>)
```

Reproducer: https://gist.github.com/QmQvl/e0f655db87098c2c8357e7600b9ca655

**Comment by jypma** [comment]
Probably fixable by making javadsl `UpgradeToWebSocket` a java-written abstract class like the other headers, instead of a scala trait.

**Comment by ktoso** [comment]
How do you mean it's impossible to get it?
Where do you need it explicitly?

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 10 November 2016 at 02:55:01, Jan Ypma (notifications@github.com) wrote:

Probably fixable by making javadsl UpgradeToWebSocket a java-written
abstract class like the other headers, instead of a scala trait.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/507#issuecomment-259660796>, or mute
the thread

**Comment by QmQvl** [comment]
Is there any other way to obtain both sides of a websocket to implement server-push model instead of request-response? Documentation states only `UpgradeToWebSocket.handleMessagesWith`.

**Comment by jrudolph** [comment]
There's `akka.http.javadsl.model.ws.WebSocket.handleWebSocketRequestWith` which is a helper you can use to install a websocket handler without having to access the header explicitly (also documented [here](http://doc.akka.io/docs/akka-http/current/java/http/server-side/websocket-support.html#example)). 

This entry-point currently only allows access to the `handleWebsocketWith(Flow)` method. Other overloads that are accessible on the header are currently not available. Is that the problem you are facing, @QmQvl? That you want specify `Source` and `Sink` instead of just the `Flow`? I'd say we should also add all those overloads to `akka.http.javadsl.model.ws.WebSocket`.

The method accepting the `Flow` is the most general one, so you can implement all kinds of behaviors, also a server-push like with this signature.

In the meantime, you can use something like this:

```scala
Source<Message> source = // a source with your server-pushed events.
WebSocket.handleWebSocketRequestWith(request, 
                Flow.fromSinkAndSource(Sink.ignore /* if not interested in client messages*/, 
                source));
```

**Comment by QmQvl** [comment]
Yes, I wanted to have a direct access to Sink and Source, so this might help.

**Comment by ktoso** [comment]
To be honest the Flow version is the nicest since you can pick if you want to bind their completion or not -- via `Flow.fromSinkAndSource` or `Flow.fromSinkAndSourceCoupled`. But we can add some convenience methods

**Comment by ktoso** [comment]
After considering some of the options, and sadly making it behave like a normal header would be potentially breaking I'll go ahead with documenting using the apropriate Flow methods to be used in conjunction with this.

**Comment by xSeagullx** [comment]
I'm afraid I also need a Java access to `UpgradeToWebSocket`, but for different reasons. I need to access and provide requested protocol for a proper handshake: i.e. access `HttpResponse handleMessagesWith(Graph<FlowShape<Message, Message>, ?> flow,
                                String protocol)` method.

**Comment by jrudolph** [comment]
@xSeagullx can you create a new ticket for this? It's probably an oversight if that API is not exposed to Java.

**Comment by jrudolph** [comment]
In 10.2.0, we replaced the header with a `WebSocketUpgrade` attribute that is better supported for Java.
