### ISSUE TITLE
In scala-http-testkit it is impossible to match pathEnd at the root of a route

### ISSUE THREAD

**Issue by mcamou** [akka/akka-http#671]
I have a route similar to this:

```
object VersionRoute {
  val route: Route = {
    pathEnd {
      get {
        complete(VersionInfo.info)
      }
    }
  }
}
```

I want to write a unit test using akka-http-testkit. However, doing `Get("") ~> Route.seal(VersionRoute.route) ~> check { ... }` gives a 404, and `Get()` gets rewritten to `Get("/")` by `Get.apply` (which -- correctly -- does not match either). The way to get around it is to wrap the route in a `pathPrefix` directive for testing purposes, but this feels like it should be unnecessary.

**Comment by jrudolph** [comment]
You cannot match an empty path at the root because you cannot make a request with an empty path in HTTP. So, this route cannot be used at the root of your routing tree. The testkit is based on requests so you cannot specify a request with an empty path.

If you want to test a subroute you it seems to be indeed the best solution to have a synthetic path prefix like you suggested.

**Comment by Matjaxon** [comment]
I believe a better solution to this change your route's directive to `pathEndorSingleSlash` rather than `pathEnd`.  Then you can use a `/` for testing.
