### ISSUE TITLE
Warning on invalid routes (get inside post)

### ISSUE THREAD

**Issue by Stivo** [akka/akka-http#694]
I am new to akka http, using version 10.0.1 on akka 2.4.16.
I sometimes end up with routes like:

     val route = post {
           getFromFile(responseFile)
     }

which if you read the code from getFromFile turns out to be:

     val route = post {
           get { 
               ... 
           }
     }

Which is clearly invalid. It would be nice if this could be detected and there could be a warning about it in some form.

**Comment by ktoso** [comment]
It would indeed be nice but is rather very difficult to implement. I'll keep the ticket but it's not something core team will work on. If someone has the time you can try, but it'll be rather very difficult to implement due to how generic the routing infrastructure is. 

If you prefer more checked routes, try Play or Lagom where such things are not possible to write anyway.

**Comment by ktoso** [comment]
PS: Please upgrade, the stable series is 10.0.x (latest 10.0.1)

**Comment by Stivo** [comment]
I am using 10.0.1, I edited it to fix that before you commented ;)

Could you then add a version of getFromFile that does not assume get? 
Or take the get out of getFromFile? Isn't get the default anyway?

**Comment by jrudolph** [comment]
I guess it could be done by adding information to the request or context when it passes a filter. When it then passes a conflicting filter it could produce a runtime error.

**Comment by raboof** [comment]
Seems like something that maybe could be detected at the tooling level, I don't think we could find a reasonable way to do it in the library.
