### ISSUE TITLE
Deprecate `extends Directives` to allow better evolvability

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#7]
Extending the `Directives` trait is a killer for binary compatibility.
What if, when going stable in akka/akka-http we say this is not supported and mark the trait as deprecated, instead people should always `import Directives._` or better, just the ones they need.

It is very "cool" to just extend Directives, however it comes with many problems as you know...
Once Scala 2.12 is out, we can support it again, because then adding directives to traits IS binary compatible.

Yay or Nay @akka/akka-http-team ?

**Comment by ktoso** [comment]
I say Yay.

**Comment by jypma** [comment]
I'm :+1: on the direction, but we should agree on a specific way of achieving this on the language level. Deprecating the trait only makes sense if we then don't extend it internally for `object Directives` either.

So how about:
- we rename the current `trait Directives` to `private[akka] trait AllDirectives`
- `object Directives extends AllDirectives`
- `@deprecated trait Directives extends AllDirectives`

For Java DSL, we'd deprecate the `abstract class AllDirectives`, and remove it from the test class hierarchy.

**Comment by ktoso** [comment]
> Deprecating the trait only makes sense if we then don't extend it internally for object Directives either.

Yes and no. Yes, for `Directives` it makes sense to do like this. However we need to do this for ALL Directives traits.

> For Java DSL, we'd deprecate the abstract class AllDirectives, and remove it from the test class hierarchy.

For Java it does not matter actually, at least not from a binary compatibility point of view. 
It is not traits, it just works if you add a new method.

So I'm not sure if deprecating in Java is needed. 

----

**Alternative 2:**

- We make all the Directives traits into classes. This solves bin-compat issues. 
  - At the expense of a day of pain doing this conversion.
  - this breaks "just mix it in", but some people may still be able to use it.
- We *recommend* the `import BlaDirectives._` way anyway.

Unless I missed something which would not be solved by that?

cc @jrudolph

**Comment by jrudolph** [comment]
> Extending the Directives trait is a killer for binary compatibility.

Can someone explain the actual issue here? Is this a blocker or just a theoretical problem? 

AFAIU the main problem is that a binary jar that extended an old version of that trait won't get the forwarders for methods that were added in a later version. This will then fail when an object that extended the old version of the trait is passed around and a binary compiled against a new version expects the method implementation to exist.

E.g. there are the modules A(0) and A(1) in two different versions and B which uses A and C which uses B.

```scala
A(0):

trait Methods {
  def base: Int
}

B:

class MethodImpl extends Methods {
  def base: Int = 5
}

C:

new MethodImpl.base // <- call method from A
```

Now, A is updated to version 1 and a new method is added:

```scala
A(1):

trait Methods {
  def base: Int

  def other: Int = base + 12
}

B isn't recompiled

C:

// call new method from A with dynamic dispatch through B's implementation
new MethodImpl.other // <- will fail with AbstractMethodError
```

However, this is not how `Directives` is commonly used. `extends Directives` is usually used as an implementation detail to get directives into scope and the resulting object is usually not passed around so that a consumer would actually call a directive method on any foreign object that extended Directives at some point. All inner uses of the changed trait are still perfectly save because a library compiled against an old version of Directives doesn't know about new ones added later.

So, I'm not sure if changing the scheme at this point wouldn't do more harm than good.

**Comment by ktoso** [comment]
It seems the one case I was worried about actually is fine. Thanks for picking up the discussion here.

To confirm, if we add a directive, and a library did not use it (since it could not), yet user wants to upgrade:

```bash
$ cat Directives.scala
trait Directives {
  def a: String = ""
}
ktoso @ 月/tmp/directives
$ cat Library.scala
trait Library extends Directives {
  def other = ""
}
ktoso @ 月/tmp/directives
$ cat User.scala
trait UserCode extends Directives with Library {}

object WebApp extends App {


  val u = new UserCode {}
  println(u)
}
ktoso @ 月/tmp/directives
$ scalac *scala
ktoso @ 月/tmp/directives
$ java -cp .:/Users/ktoso/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.6.jar WebApp
WebApp$$anon$1@566776ad
ktoso @ 月/tmp/directives
$ vim Directives.scala

# we add a new directive ---------------
ktoso @ 月/tmp/directives
$ cat Directives.scala
trait Directives {
  def a: String = ""
  def b = 21
}
ktoso @ 月/tmp/directives
$ scalac Directives.scala
ktoso @ 月/tmp/directives
$ scalac User.scala # user upgrades code ---------------
# the Library is not recompiled against new X.Y.Z ---------------

ktoso @ 月/tmp/directives
$ java -cp .:/Users/ktoso/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.6.jar WebApp
WebApp$$anon$1@566776ad # we're good
```

I'll try to find the specific case where people started complaining that we broke their libraries (though it was experimental so meh).

**Comment by ktoso** [comment]
Ok, so there is no reason to deprecate this style - good!
