### ISSUE TITLE
Inconsistent logging of request body by logRequestResult directive

### ISSUE THREAD

**Issue by jaroslawr** [akka/akka-http#704]
logRequestResult will log the request body if the entity is HttpEntity.Strict, but will not log it for HttpEntity.Default, which is surprising and makes debugging hard. It comes down to the implementation of toString() in HttpEntity.Default:

https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala#L395

**Comment by ktoso** [comment]
Because Default is a stream and you'd have to consume the stream in order to "print the entire thing". toString suddenly causing consumption of the TCP stream would be seen as weird and dangerous side effect IMHO.

What were you expecting?

**Comment by jaroslawr** [comment]
@ktoso Perhaps then logRequestResult should not use toString() but implement it's own pretty printing of the entity? I don't know the internals of akka-http, I can understand there might be implementation difficulties, but from the standpoint of a user of the library there does not seem to be a logical reason to print the body in one case but not in another, especially that both entity classes mentioned represent very similar simple (not chunked etc.) requests.

**Comment by ktoso** [comment]
The entity *could* be a gigabyte of data. And you won't know until you start reading it. So such toString would effectively disable any backpressure on that entity.

It is not implementation difficulties, it is semantics that need to be not-surprising and correct. 
If you can propose some set of semantics that would make sense we could consider it or you could provide a PR.

I don't agree that the solution has anything to do with "just log it" since that would be basically side effecting and breaking many things for users. It does relate to https://github.com/akka/akka-http/issues/117 and I'd rather close this ticket as the auto-draining would both solve it, and not lead to any suprising behaviour, as any hotfixing inside the logging directives would.

Sounds like a plan?

**Comment by ktoso** [comment]
If you don't care about these you can simply wrap your route in `toStrictEntity` so things will be logged the Strict way, since everything will be strict-ified.

I propose to close since a) above solution works now b) liked ticket could be a great enchancement in the future.

**Comment by jaroslawr** [comment]
@ktoso I know very little about akka-http internals, so I am not able to propose an implementation strategy, I have some broad comments though:
* As far as I understand, exactly the same HTTP requests can get represented as HttpEntity.Default or as HttpEntity.Strict depending on the circumstances, so I think it indeed is an implementation difficulty and not a problem that would have any deep logical roots in the problem being solved. 
* Content-Length is present both of those entity classes so you do know how large the entity is up-front.
* logRequestResult pretty-prints the request/response in a very specific moment in the request/response lifecycle, while toString() needs to be generic enough to represent the object in any possible state, so it might make sense to e.g. have a specialized variant of a toString() method. I doubt this necessarily implies hotfixing, surprising behaviour, or breaking anything, but then I am not that familiar with the codebase. In any case, to me the current behavior is broken and surprising, I should not need to learn anything about akka-http internals to get decent logging in place.

**Comment by jrudolph** [comment]
Hi @jaroslawr,

the inconsistency is well-known. You are right that the on-wire format is the same for both `HttpEntity.Strict` and `HttpEntity.Default`, the dynamic behavior (or "the circumstances") are different. `Strict` is an entity that has been fully received, `Default` is an entity where complete data hasn't been received yet.

There's only one way to make it consistent which would be never logging the body in both cases. This way we could show the same representation for the same on-wire format. However, at the same time we would also conceal details about the dynamic behavior.

It's arguable whether it would have been possible to get away without modeling `HttpEntity.Strict` explicitly. But that's not the way it is. It's arguable whether this could be pulled off.

Anyway, with regard to this ticket, @jaroslawr, do you have any suggestion what to improve?

**Comment by jaroslawr** [comment]
@jrudolph Doesn't logRequestResult log the request and response after they have been completely received? That's what I would expect, at least in case of non-chunked requests. In particular what annoys me is that I get HttpEntity.Default and no entity body in the logs whenever there is a rejection from the router, which is often precisely where I need the information most.

In any case, there should be a way to get the request/response body logged without at the same time giving up streaming (what asStrictEntity implies) and without having to study akka-http internals. It's just a pretty basic feature for a HTTP library. That's all, I am sorry I am not able to provide more specific technical suggestion.

**Comment by ktoso** [comment]
Jarosław, if you want to "log the entity" it needs to be read in, which is exactly "to stricting the entity". You may call it streaming still since the way the entity was read in, well, was a stream. But in order to "log the entire entity" you have to have it strictly in memory, there is no way around it - this is not a library limitation, this is a fact.

We've provided a workaround a) toStrictEntity, and explained why toStricting is needed for logging the entity, there also is a missing feature called auto-to-strict/draining which is logged here:  https://github.com/akka/akka-http/issues/117 as was pointed out above.

I don't see this ticket adding more to the discussion, since the above workaround and missing feature address these needs. Thanks for chiming in, closing the ticket though as it's better to action on the https://github.com/akka/akka-http/issues/117 issue rather than this specific ticket.
