### ISSUE TITLE
Maintain and publish a changelog for Akka HTTP

### ISSUE THREAD

**Issue by sarahgerweck** [akka/akka-http#819]
It's standard for software to make available a change log that describes all the nontrivial changes that are part of each release, often as a `CHANGELOG(.md)` in the root of the source repository. (It could also just be in the docs.)

This is especially important for a framework like Akka HTTP that provides critical application infrastructure. As a maintainer of production software that uses Akka HTTP, I really need to be able to assess the impact to my project of an update to the version Akka HTTP. (E.g., do I need to change my code to adjust for any behavior changes? Are there any areas where I need to do additional acceptance testing?)

Without an official change log, it is much more difficult for me to stay current. I basically have to read the source history to try to see what's change—or make a leap of faith that any changes of consequence will be discovered by the compiler or my tests rather than by my customers. (It also makes it less likely that I'll start using new features.)

I know this is a new project and there are lots of important things that need work, but I really think this is a must-have for a project like Akka. (I apologize in advance if this already exists, but I can't find anything like this other than the blog posts. If they always have thorough change lists, then perhaps they can be linked from the documentation or copied into the GitHub repo.)

**Comment by jrudolph** [comment]
Thanks for the suggestion, @sarahgerweck. 

Until now we have published news items on our blog that included at least the highlights of the new version. That would also be the place where we would mention any critical changes. We also tried to maintain the github milestone to give an accurate view of what was fixed in a version. We tried to stay binary compatible in the 10.0.0 line and should also be mostly binary compatible with the older still experimental versions. But you are right that small behavioral changes that are not covered by the static binary compatibility guarantees might still have an influence.

So, overall, I think you could see our release announcements as a changelog (that's also how [netty](http://netty.io/news/index.html) seems to be doing things). However, these news items are not so easy to find and it's hard to get an overview over what has changed over a longer term. 

I'd propose to add a page to the documentation which lists notable changes (and links to potential migration guides) per version in reverse chronological order. It should be linked from the documentation, the sources, and the news item on the blog (which may also copy part its content). 

The question is always how to maintain that. For now, I'd say we manually collect it during the release process. We may build a simple script which takes a milestone and gets the tickets that were closed in that timeframe and builds a markdown snippet out of it to use as a base for the changelog entry.

@akka/akka-http-team WDYT?

**Comment by ktoso** [comment]
Hi there, good points but let's step back and see what we have (because we do post such information in a trackable way) and what it is you were expecting.

Firstly, all releases have milestones with all the issues solved by them attached, e.g. for 10.0.2: https://github.com/akka/akka-http/milestone/20?closed=1

I think that that list is the level of detail you need most of the time. I see you may want the issues grouped by modules which they affect, like Spray (Akka HTTP's predecessor) did, but that's a convenience thing really. Most other projects I track do it the same way (including netty, spark and others). 

I see where whis question may have come from though, it seems we forgot to link to it in the last announcement on akka.io/news which I'll fix right away => https://github.com/akka/akka.github.com/commit/c259c61604ed9c07513ac1006bcec78995c7f626 & https://github.com/akka/akka.github.com/blob/master/news/_posts/2016-12-22-akka-http-10.0.1-released.md
Please note that that release explicitly mentions that only the single thing was fixed in it since 10.0.1.

I don't think adding an automatically produced changelog file would help in anything here. We have the issues tracked properly as I pointed out. For bigger changes we always call them out in news items - which are the "curated" changelog.

Johannes's idea with the additional docs page about linking to migration pages is more useful I think. We can improve here, but would also make sure that the notes are consistent between Akka and Akka HTTP, so we'll see what makes sense for both projects.

I'm tempted to rename the title of the issue somewhat, since it is not really about the CHANGELOG file which we don't think adds much value, but a different way of exposing this information.

**Comment by ktoso** [comment]
Any help on this front by providing scripts which would help maintain such notes would be very welcome and increase the likelihood of this being addressed tenfold btw, thanks in advance!

**Comment by jlprat** [comment]
What about providing some links on the release page in Github (and user lists and akka.io/news) that point to github itself showing what has been changed?
For example: 
* For low level check of what has been changed: https://github.com/akka/akka-http/compare/v10.0.1...v10.0.2
* For a higher-level view: https://github.com/akka/akka-http/issues?q=is%3Aissue+milestone%3A10.0.3+is%3Aclosed (link to all milestoned closed issues)
* For even a higher level one: Link to migration guide for specific version

**Comment by ktoso** [comment]
Yeah, well summed up I think 👍 
Not sure we need anything more, at least from my perspective.

Please note that we keep binary compatibility unless we call it out explicitly in a news item.

**Comment by jlprat** [comment]
AFAIK you (akka-team) is providing the release notes, but maybe we could create some page in the documentation that shows this information so you could just copy paste it from there :)

**Comment by sarahgerweck** [comment]
Yeah, I have no attachment to an actual `CHANGELOG` file if you all feel that you're already generating this information. What I _would_ hope to see is an easy-to-find link to the recommended way(s) of identifying what's changed.

**Comment by ktoso** [comment]
Ok, let's give a somewhat improved notes a spin during the next release then (and then close this ticket).

Call for help for semi automating these things is still valid though ;-)
If someone would like to help categorising PRs in such log by module which they touched etc.

**Comment by jonas** [comment]
Maintaining a changelog amortizes the cost of doing a release across all changes and avoids having to wade through tons of commits or milestones to get the release out and write an announcement. Automating this would require very good ticket titles, which is hard and with GitHub there's no way to divide them in to sections about breaking changes, new features/improvements, bug fixes etc.

I would be up to help get this effort started.

**Comment by ktoso** [comment]
> with GitHub there's no way to divide them in to sections about breaking changes, new features/improvements, bug fixes etc.

In Akka we had actually commit message patterns which allowed for this. We never automated it though, `+htc` `!htc` etc, new apis, breaking apis etc were marked as such

**Comment by jrudolph** [comment]
Added shiny new release notes section to documentation in #837. Thanks again for the suggestion, @sarahgerweck.

**Comment by ktoso** [comment]
👍

**Comment by jrudolph** [comment]
@jonas I just remembered that we had a very strict commit line policy in spray for this very reason. But as the number of committers was far smaller, it was also easier to enforce. We let go of this strictness and now have to do a bit of extra work to figure out the commits. What I found is that we should probably enforce putting the issue number in the commit line. This already helps a lot.

**Comment by sarahgerweck** [comment]
I just want to say that I used the new docs this evening to check out the 10.0.3 changes and it's great. I'm impressed at how this was done quickly, and it looks great. Kudos and thank you. :clap:
