### ISSUE TITLE
Sink returned by `StreamConverters.asOutputStream` does not work with akka-http

### ISSUE THREAD

**Issue by note** [akka/akka-http#872]
Running endpoint GET "stream" against following code: https://gist.github.com/note/b7869c1a72baa0a4c583c400f7bda919 ends up in server closing the connection after a few seconds and following message in logs: https://gist.github.com/note/1726714adf7dffd856a9715b338812a5

I submit it as bug in akka-http because as you see in above code running exactly the same `Source` with `source.runWith(Sink.foreach(str => println(s"Some string: ${str.utf8String}")))` works as expected.

Also did a little experiment and build akka-http with changed line https://github.com/akka/akka-http/blob/5932237a86a432d623fafb1e84eeeff56d7485fe/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala#L112 to `outStream.runWith(sinkIn.sink)(interpreter.materializer)` and then it worked as expected (so `interpreter.materializer` instead of `interpreter.subFusingMaterializer`). I have not enough knowledge to interpret result of this experimentation, just sharing some observation.

**Comment by jrudolph** [comment]
Hi @note,

yes, I think that makes sense. When it works you rely on the fact that your (blocking!) `mapMaterializedValue` operation and the actual initialization of the `asOutputStream` stage are run on different threads. It will break down if the initialization of the stage is deadlocked by a blocking call in `mapMaterializedValue`.

So, I'd say this works as expected. If you use blocking APIs without explicit management you may run into starvation and deadlock issues. This is what happens if you use the blocking `OutputStream` API from the `mapMaterializedValue` block. If you run this code block on another thread (e.g. using `Future { blocking {...} }`) it should work.

I'm closing this for now. Feel free to reopen or continue discussing if something is still unclear.
