### ISSUE TITLE
HttpApp - should it extend App

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#874]
Since the main use case is to make it 1 liners to have an "App" and the name suggests "Http**App**"... should it extend App?

What would be the downside?

**Comment by jlprat** [comment]
First iterations of `HttpApp` had a main, but general feedback was that it was not needed because most of the times the HTTP server was not the only thing they were running and some other non related tasks needed to be run/setup.

We could give it a try, making it "dual", so it could run as `App`, but also by simply calling `startServer`.

**Comment by jlprat** [comment]
Making `HttpApp` extend `App` makes our current examples (and tests) fail, because of deferred initialization. As our tests, don't really run the `App`, but just call the `startServer` method, there are some NPE when trying to access any field that must be defined.

So, making `HttpApp` extend `App` would fit to the use case you want to show (provide the most minimalist way to start a server) but it might complicate the use for the cases where `HttpApp` is used within an existing bigger app, and also our tests.

WDTY?

**Comment by ktoso** [comment]
I think it may be fine to keep it not extend app hm...

Heading offline now for some days, talk to you later :)

**Comment by jlprat** [comment]
Have a nice one!

**Comment by jrudolph** [comment]
I think we attempted something similar in spray but we found it hard to get it to work properly with `DelayedInit`.

**Comment by jlprat** [comment]
Current version might be not that bad, as we give some freedom to the user, if must be a stand-alone app, just mix in `App`. Otherwise, just run it with `startServer`

**Comment by jrudolph** [comment]
I think this has been superseded by reality. I agree with @jlprat that the current version is good enough. Closing this for now.

**Comment by ktoso** [comment]
I've grown to like the current style through the few projects I contributed to recently and made use of this :)
Good to keep a is 👍
