### ISSUE TITLE
Allow conversion from Java Route to Scala Route

### ISSUE THREAD

**Issue by atduarte** [akka/akka-http#891]
There's a way to convert a Scala Route (`akka.http.scaladsl.server.Route`) to a Java Route (`akka.http.javadsl.server.Route`) by using the RouteAdapter (`akka.http.javadsl.server.directives.RouteAdapter`). 
Although **there's no way to do it the other way around**.

The Java Route already has the `delegate` method, but it's `private[http]` and it's marked as "INTERNAL API". 

Should we change this method's privacy or add this functionality in a different way?

**Comment by jypma** [comment]
I see no problem introducing a public `.asScala` on the Java variant that returns `delegate`, since the same is available for the `Flow` Java DSL.

**Comment by jypma** [comment]
@atduarte would you be willing to create a PR for this?

**Comment by lomigmegard** [comment]
Note that this is related to #661. The `JavaMapping`s are also `private[http]` and therefore adding a `.asScala` implicit for the Java Route will not help third-party libraries. 

Current workaround:
```scala
val javaRoute = ??? // for example inner.get()
val scalaRoute = javaRoute match {
  case ra: RouteAdapter => ra.delegate
}
```

**Comment by ktoso** [comment]
I think this one's a pretty fair point and we can open it up before the JavaMappings even perhaps... just as plain old methods, similar how in the "main things" (flow etc) we do so in Akka Streams.


I'll give it a look and also re-consider the https://github.com/akka/akka-http/issues/661 ticket again at the same time, since we wanted to open it up a bit since Alpakka was requesting it... though for starters may be just private[akka]-ing it...
