### ISSUE TITLE
Allow to configure ClientTransport with application.conf

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#995]
Right now it can only be done in code. The facility should allow to specify parameters, e.g. the upcoming HTTPS proxy transport needs a host and port configuration.

**Comment by jiminhsieh** [comment]
It seems have to add 2 properties to  `akka.http.client` in application.conf. Do you have any idea of how this format should be? It could be `akka.http.client.https-proxy.host` or `akka.http.client.https-proxy-host`. Thanks!

**Comment by jiminhsieh** [comment]
@jrudolph It seems original client proxy had been removed at #1249. So the format should likes?
```
akka.http {
  client {
    proxy {
      https {
        host = myproxy.com
        port = 8080
      }
    }
  }
}
```
Thanks!

**Comment by raboof** [comment]
@jiminhsieh Right, that's what it looked like in Spray - sounds good to keep that general approach!

**Comment by jiminhsieh** [comment]
After I traced through Spary’s source code, I have some questions. I would post full of original format of spray proxy config first.

```
spray.can {
  client {
    proxy {
      http {
      	host = myproxy.com
      	port = 8080
      }
      https = {default, none}
    }
  }
}
```

There are my questions: 
1. Does it need to support system properties which was represent as `default` in Spray?
2. Does it need `none` in addition to `default`? If it has `none`, should we use `none` as default value instead of `default`?

There is my idea of how to implement it. Create public API, `httpsProxy` without parameter, for client. The rest of code would be similar to Spary with current design of Akka-HTTP which split to abstract class and case class of `-impl`.

If there is any hint or suggestion, I will be glad to listen. : )
